### ISSUE TITLE
An error occurs when accessing the checkout endpoint with any currency other than USD.

### ISSUE THREAD

**Issue by tkhs0813** [airbadge-dev/airbadge#15]
I am trying the example, and I get an error when creating a product in JPY.
Is it possible to support currencies other than USD as well?

https://github.com/airbadge-dev/airbadge/blob/11e75208c3c5b285af9757f8ec1944a0ad47d646/packages/sveltekit/src/lib/server/billing.js#L52

error message: 
```
The price specified supports currencies of `jpy` which doesn't include the expected currency of `usd`.
```

**Comment by joshnuss** [comment]
Thanks @tkhs0813, I'll take a look
