### ISSUE TITLE
Documentation does not mention setting up AUTH_SECRET

### ISSUE THREAD

**Issue by fabianmossberg** [airbadge-dev/airbadge#6]
In the documentation, when [configuring the environment](https://docs.airbadge.dev/getting-started#configure-environment), there is no mention of the `AUTH_SECRET` env variable.

Without it, I got the following error:

```
[auth][error] TypeError: "ikm"" must be an instance of Uint8Array or a string
```

I followed [these instructions](https://authjs.dev/getting-started/installation?framework=sveltekit#setup-environment
) to get rid of it:

```sh
$ npx auth secret

Secret generated. Copy it to your .env/.env.local file (depending on your framework):
AUTH_SECRET=rcDZnCY....
```

This should probably be added to the documentation.

**Comment by joshnuss** [comment]
Resolved:
https://github.com/airbadge-dev/airbadge/blob/290a0a66f35e9a7b5289a5092088cc56d379e9bd/apps/docs/src/routes/getting-started/%2Bpage.md?plain=1#L36-L38
